### ISSUE TITLE
I am having issues running json from my terminal

### ISSUE THREAD

**Issue by Younique98** [nss-day-cohort-46/How-to-Ask-for-Help#55]
**_Ticket MUST be completed before getting help from an instructor_**

#### Book / Chapter: 
Hairy Potter

#### Have you searched the other issue tickets? If not, do that first. 
- [ x] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [ ] Added label to specific project/assignment that you need help with
- [ ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>>

#### REQUIRED List any error messages that appear:

//
Error: Type of "name" (string)  is not supported. Use objects or arrays of objects.
    at /usr/local/lib/node_modules/json-server/lib/server/router/index.js:83:11
    at /usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:2990:24)
    at /usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:9368:14)
    at /usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:4388:28
    at arrayReduce (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:4387:14)
    at LodashWrapper.wrapperValue (/usr/local/lib/node_modules/json-server/node_modules/lodash/lodash.js:9072:14)
    at Object.module.exports [as router] (/usr/local/lib/node_modules/json-server/lib/server/router/index.js:84:6)
//
#### REQUIRED What have you googled? **_(You must have at least 3 links related to your issue)_**

- [https://stackoverflow.com/questions/46195599/type-of-id-number-in-user-json-is-not-supported-use-objects-or-arrays-of-ob ] 1. 
- [ https://github.com/typicode/json-server/issues/435] 2. 
- [ https://github.com/typicode/json-server/issues/832] 3. 

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>>
I tried changing the file structure by adding [] and naming the first array 'files'

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

**Your link:**
https://github.com/nss-day-cohort-46/hairy-potter-Younique98/blob/505f0228597dfc5cef6be3dc119aa3b93685b6ac/package.json#L1
#### Code Snippet

```
PASTE YOUR CODE HERE BETWEEN THE BACKTICS
```
 Type of "name" (string)  is not supported. Use objects or arrays of objects.

**Comment by Younique98** [comment]
DIdn't need to serve package.json
